import type { Project, Location, Task, LocationPhoto } from './types'

export const sampleProjects: Project[] = [
  {
    id: 'project-1',
    title: '男性アイドル MV',
    clientName: 'スターレコード株式会社',
    shootDescription: '前向きで軽快な新曲のMV。屋外・自然光・開放感のあるロケーションを検討。',
    shootDates: [],
    candidateDates: [
      { id: 'date-1', date: '2025-06-16' },
      { id: 'date-2', date: '2025-06-17' },
      { id: 'date-3', date: '2025-06-22' },
      { id: 'date-4', date: '2025-06-23' },
    ],
    budget: '200万円',
    requirements: '夕景、控室あり、車両2台、音出し確認、雨天時の代替案',
    pmName: '田中 美咲',
    directorName: '鈴木 大輔',
    memo: '衣装は白ベース。ゴールデンアワーの光を最重要視。',
    status: 'on_hold',
    createdAt: '2025-05-20T09:00:00.000Z',
    updatedAt: '2025-05-28T14:30:00.000Z',
  },
]

export const sampleLocations: Location[] = [
  {
    id: 'loc-1',
    projectId: 'project-1',
    name: 'ファームリゾート御宿',
    address: '千葉県夷隅郡御宿町田代831-2',
    mapUrl: 'https://maps.google.com/?q=ファームリゾート御宿',
    officialUrl: '',
    contactName: '山田 健一',
    phone: '0470-68-XXXX',
    email: 'info@farm-onjuku.example.com',
    price: '¥22,000 + 延長 ¥8,000/h',
    availableTime: '13:00〜18:00',
    extensionFee: '¥8,000/時間',
    cancellationPolicy: '3日前まで無料。前日50%、当日100%。',
    paymentTerms: '銀行振込（撮影1週間前まで）',
    parking: 'yes',
    waitingRoom: 'unknown',
    power: 'yes',
    toilet: 'yes',
    makeupRoom: 'unknown',
    rainSupport: 'partial',
    soundAllowed: 'yes',
    fireAllowed: 'no',
    permissionStatus: '申請済み',
    ngRules: 'ドローン使用不可、農場エリアへの立入禁止',
    loadingRules: '機材車は専用駐車場へ',
    vehicleLimit: '普通車3台、2tトラック1台',
    peopleLimit: '30名以内',
    usableArea: 'ガーデン全域、古民家前エリア',
    status: 'hold',
    dateAvailability: {
      'date-1': 'available',
      'date-2': 'unavailable',
      'date-3': 'checking',
      'date-4': 'available',
    },
    lastContactDate: '2025-05-25',
    nextFollowUpDate: '2025-06-01',
    memo: '夕景のゴールデンアワーが最も美しい。ただし17:30以降は追加料金が発生する可能性あり。',
    photos: [
      { id: 'ph-1', url: 'https://picsum.photos/seed/onjuku-garden/800/500', label: '外観', caption: 'ガーデン全景' },
      { id: 'ph-2', url: 'https://picsum.photos/seed/onjuku-house/800/500', label: '内観', caption: '古民家内部' },
      { id: 'ph-3', url: 'https://picsum.photos/seed/onjuku-park/800/500', label: '駐車場', caption: '機材車スペース' },
    ] as LocationPhoto[],
    contactHistory: [
      {
        id: 'ch-1',
        date: '2025-05-20',
        method: 'メール',
        content: '初回問い合わせ。料金表と空き状況を確認。',
      },
      {
        id: 'ch-2',
        date: '2025-05-25',
        method: '電話',
        content: '6/16と6/23の仮キープを依頼。了承いただいた。',
      },
    ],
    createdAt: '2025-05-20T10:00:00.000Z',
    updatedAt: '2025-05-25T16:00:00.000Z',
  },
  {
    id: 'loc-2',
    projectId: 'project-1',
    name: '都内ハウススタジオ BLANC',
    address: '東京都渋谷区恵比寿2-3-XX',
    mapUrl: 'https://maps.google.com/?q=恵比寿+ハウススタジオ',
    officialUrl: '',
    contactName: '佐藤 裕子',
    phone: '03-XXXX-XXXX',
    email: 'reserve@blanc-studio.example.com',
    price: '確認中',
    availableTime: '10:00〜22:00',
    extensionFee: '',
    cancellationPolicy: '',
    paymentTerms: '',
    parking: 'yes',
    waitingRoom: 'yes',
    power: 'yes',
    toilet: 'yes',
    makeupRoom: 'yes',
    rainSupport: 'yes',
    soundAllowed: 'confirm',
    fireAllowed: 'unknown',
    permissionStatus: '',
    ngRules: '',
    loadingRules: '',
    vehicleLimit: '1台',
    peopleLimit: '',
    usableArea: '',
    status: 'waiting',
    dateAvailability: {
      'date-1': 'unknown',
      'date-2': 'unknown',
      'date-3': 'unknown',
      'date-4': 'unknown',
    },
    lastContactDate: '2025-05-22',
    nextFollowUpDate: '2025-05-30',
    memo: '返信がまだない。もう一度連絡が必要。',
    photos: [
      { id: 'ph-4', url: 'https://picsum.photos/seed/blanc-front/800/500', label: '外観', caption: 'エントランス' },
      { id: 'ph-5', url: 'https://picsum.photos/seed/blanc-studio/800/500', label: '内観', caption: 'メインスタジオ' },
      { id: 'ph-6', url: 'https://picsum.photos/seed/blanc-makeup/800/500', label: '控室', caption: 'メイクルーム' },
    ] as LocationPhoto[],
    contactHistory: [
      {
        id: 'ch-3',
        date: '2025-05-22',
        method: 'メール',
        content: '候補日の空き確認と料金の問い合わせを送信。',
      },
    ],
    createdAt: '2025-05-22T11:00:00.000Z',
    updatedAt: '2025-05-22T11:00:00.000Z',
  },
  {
    id: 'loc-3',
    projectId: 'project-1',
    name: '海沿い公園（鎌倉）',
    address: '神奈川県鎌倉市材木座海岸',
    mapUrl: 'https://maps.google.com/?q=鎌倉+材木座海岸',
    officialUrl: '',
    contactName: '鎌倉市公園課',
    phone: '0467-XX-XXXX',
    email: '',
    price: '許可申請費用のみ',
    availableTime: '日の出〜日没',
    extensionFee: '',
    cancellationPolicy: '',
    paymentTerms: '',
    parking: 'yes',
    waitingRoom: 'no',
    power: 'no',
    toilet: 'yes',
    makeupRoom: 'no',
    rainSupport: 'no',
    soundAllowed: 'confirm',
    fireAllowed: 'no',
    permissionStatus: '申請準備中',
    ngRules: '音出し要確認、ドローン撮影別途許可必要',
    loadingRules: '',
    vehicleLimit: '',
    peopleLimit: '',
    usableArea: '海岸エリア',
    status: 'pending',
    dateAvailability: {
      'date-1': 'unknown',
      'date-2': 'unknown',
      'date-3': 'unknown',
      'date-4': 'unknown',
    },
    lastContactDate: '',
    nextFollowUpDate: '',
    memo: '控室・電源なし。雨天時の代替が必要。夕景は非常に美しい。許可申請に2週間かかる可能性あり。',
    photos: [
      { id: 'ph-7', url: 'https://picsum.photos/seed/kamakura-ocean/800/500', label: '外観', caption: '材木座海岸の眺め' },
      { id: 'ph-8', url: 'https://picsum.photos/seed/kamakura-sunset/800/500', label: '周辺', caption: '夕景イメージ' },
    ] as LocationPhoto[],
    contactHistory: [],
    createdAt: '2025-05-24T09:00:00.000Z',
    updatedAt: '2025-05-24T09:00:00.000Z',
  },
]

export const sampleTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'project-1',
    title: 'ファームリゾート御宿の仮キープ確認',
    category: 'location',
    assignee: '田中 美咲',
    dueDate: '2025-06-01',
    status: 'arranged',
    memo: '6/16と6/23でキープ済み',
    createdAt: '2025-05-25T10:00:00.000Z',
    updatedAt: '2025-05-25T16:00:00.000Z',
  },
  {
    id: 'task-2',
    projectId: 'project-1',
    title: 'BLANC スタジオ返信フォローアップ',
    category: 'location',
    assignee: '田中 美咲',
    dueDate: '2025-05-30',
    status: 'todo',
    memo: '5/22に送ったメールの返信なし',
    createdAt: '2025-05-22T12:00:00.000Z',
    updatedAt: '2025-05-22T12:00:00.000Z',
  },
  {
    id: 'task-3',
    projectId: 'project-1',
    title: '鎌倉市公園課へ撮影許可申請',
    category: 'permit',
    assignee: '田中 美咲',
    dueDate: '2025-06-05',
    status: 'todo',
    memo: '申請書類を確認してから提出',
    createdAt: '2025-05-24T09:30:00.000Z',
    updatedAt: '2025-05-24T09:30:00.000Z',
  },
  {
    id: 'task-4',
    projectId: 'project-1',
    title: '機材車（2tトラック）手配',
    category: 'vehicle',
    assignee: '山本 翔',
    dueDate: '2025-06-10',
    status: 'todo',
    memo: '',
    createdAt: '2025-05-26T10:00:00.000Z',
    updatedAt: '2025-05-26T10:00:00.000Z',
  },
  {
    id: 'task-5',
    projectId: 'project-1',
    title: 'ケータリング業者選定',
    category: 'catering',
    assignee: '山本 翔',
    dueDate: '2025-06-08',
    status: 'checking',
    memo: '3社から見積もり取得中',
    createdAt: '2025-05-26T10:00:00.000Z',
    updatedAt: '2025-05-27T09:00:00.000Z',
  },
]
